#
# Makefile for HTC Athena
#

obj-$(CONFIG_MACH_HTCATHENA)		+= htcathena.o
obj-$(CONFIG_HTCATHENA_VSFB)		+= htcathena_vsfb.o
obj-$(CONFIG_HTCATHENA_SOUND)		+= htcathena_audio.o
obj-$(CONFIG_HTCATHENA_DPRAM)		+= htcathena_dpram_core.o
obj-$(CONFIG_HTCATHENA_PHONE)		+= htcathena_phone.o

#obj-$(CONFIG_HTCATHENA_BLUETOOTH)	+= htc_bt.o 
#obj-$(CONFIG_HTCATHENA_GPS)		+= htc_gps.o
#obj-$(CONFIG_HTCATHENA_CPLD1)		+= htcathena_cpld1.o
#obj-$(CONFIG_HTCATHENA_CPLD2)		+= htcathena_cpld2.o
