#
# Makefile for ALSA
#
snd-sa11xx-uda1341-objs		:= sa11xx-uda1341.o
snd-aaci-objs			:= aaci.o devdma.o
snd-pxa2xx-pcm-objs		:= pxa2xx-pcm.o
snd-pxa2xx-ac97-objs		:= pxa2xx-ac97.o
snd-pxa2xx-i2sound-objs		:= pxa2xx-i2sound.o
snd-htcathena_audio.objs	:= htcathena_audio.o
snd-ak4641-objs 		:= ak4641.o

obj-$(CONFIG_SND_SA11XX_UDA1341)	+= snd-sa11xx-uda1341.o 
obj-$(CONFIG_SND_ARMAACI)		+= snd-aaci.o
obj-$(CONFIG_SND_PXA2XX_PCM)		+= snd-pxa2xx-pcm.o
obj-$(CONFIG_SND_PXA2XX_AC97)		+= snd-pxa2xx-ac97.o
obj-$(CONFIG_SND_PXA2xx_I2SOUND)	+= snd-pxa2xx-i2sound.o
obj-$(CONFIG_SND_AK4641)		+= snd-ak4641.o
