/* 
 * include/asm-arm/arch-pxa/htcathena-asic.h
 * History:
 *
 */

#ifndef _HTCATHENA_ASIC_H_
#define _HTCATHENA_ASIC_H_

#define HTCATHENA_W2284_BASE_PHYS	PXA_CS1_PHYS
#define HTCATHENA_W2284_CTRL_PHYS	PXA_CS1_PHYS+0x00010000
#define HTCATHENA_W2284_MMC_PHYS	PXA_CS1_PHYS+0x00200000

#define HTCATHENA_CPLD1_BASE		PXA_CS2_PHYS

#define HTCATHENA_EGPIO_CPLD2_BASE_0	PXA_CS2_PHYS+0x01000000	/* board id! */
#define HTCATHENA_EGPIO_CPLD2_BASE_1	PXA_CS2_PHYS+0x02000000 /* board id! */

#define HTCATHENA_DPRAM_BASE		PXA_CS4_PHYS

extern void      htcathena_cpld2_set( u_int16_t bits );
extern void      htcathena_cpld2_clr( u_int16_t bits );
extern u_int16_t htcathena_cpld2_get(void);

/*
 * CPLD EGPIOs
 */

#define CPLD1_EGPIO_BASE		1*GPIO_BASE_INCREMENT

#define HTCATHENA_CPLD1_EGPIO(bank,bit) (CPLD1_EGPIO_BASE + 16*bank + bit)

#define EGPIO1_HTCATHENA_BT_PWR1	HTCATHENA_CPLD1_EGPIO(0, 4)
#define EGPIO1_HTCATHENA_BT_PWR2	HTCATHENA_CPLD1_EGPIO(0, 5)

#define EGPIO1_HTCATHENA_CAM		HTCATHENA_CPLD1_EGPIO(1, 1)
#define EGPIO1_HTCATHENA_PHONE_POWER	HTCATHENA_CPLD1_EGPIO(1, 2)
#define EGPIO1_HTCATHENA_PHONE_RESET	HTCATHENA_CPLD1_EGPIO(1, 3)

#define EGPIO1_HTCATHENA_WIFI_POWER1	HTCATHENA_CPLD1_EGPIO(2, 3)
#define EGPIO1_HTCATHENA_EPSON_POWER	HTCATHENA_CPLD1_EGPIO(2, 4)

#define EGPIO1_HTCATHENA_WIFI_POWER2	HTCATHENA_CPLD1_EGPIO(2, 6)
#define EGPIO1_HTCATHENA_USB_PUEN	HTCATHENA_CPLD1_EGPIO(2, 7)

#define EGPIO1_HTCATHENA_GPS_POWER	HTCATHENA_CPLD1_EGPIO(3, 0)
#define EGPIO1_HTCATHENA_ATI_POWER1	HTCATHENA_CPLD1_EGPIO(3, 2)
#define EGPIO1_HTCATHENA_ATI_POWER2	HTCATHENA_CPLD1_EGPIO(3, 4)

#define EGPIO1_HTCATHENA_SDIO_POWER	HTCATHENA_CPLD1_EGPIO(3, 6)

#define EGPIO1_HTCATHENA_BT_WAKEUP	HTCATHENA_CPLD1_EGPIO(4, 0)
#define EGPIO1_HTCATHENA_HPEP		HTCATHENA_CPLD1_EGPIO(4, 1)
#define EGPIO1_HTCATHENA_HPEXT		HTCATHENA_CPLD1_EGPIO(4, 2)
#define EGPIO1_HTCATHENA_USB_DETECT	HTCATHENA_CPLD1_EGPIO(4, 4)
#define EGPIO1_HTCATHENA_TVOUT		HTCATHENA_CPLD1_EGPIO(4, 6)

#define EGPIO1_HTCATHENA_ISP1582_ON	HTCATHENA_CPLD1_EGPIO(6, 5)

#define CPLD2_EGPIO_BASE		2*GPIO_BASE_INCREMENT

#define EGPIO2_HTCATHENA_ATI_RESET	CPLD2_EGPIO_BASE+1

#define EGPIO2_HTCATHENA_BOARDID0	CPLD2_EGPIO_BASE+13
#define EGPIO2_HTCATHENA_BOARDID1	CPLD2_EGPIO_BASE+14
#define EGPIO2_HTCATHENA_BOARDID2	CPLD2_EGPIO_BASE+15

#endif /* _HTCATHENA_ASIC_H */
